# Generated by Django 5.2.5 on 2025-08-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="user_logo/", verbose_name="Logo"
            ),
        ),
    ]
