# Generated by Django 5.2.5 on 2025-09-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_pendingverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fcm_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="lang",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian"), ("uz", "Uzbek")],
                default="uz",
                help_text="Preferred language for the user",
                max_length=20,
                verbose_name="Language",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notification_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="test_user",
            field=models.BooleanField(
                default=False, help_text="Test uchun foydalanuvchi"
            ),
        ),
    ]
