# Generated by Django 5.2.5 on 2025-08-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="image_en",
            field=models.ImageField(
                null=True, upload_to="banner_images/", verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="image_ru",
            field=models.ImageField(
                null=True, upload_to="banner_images/", verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="image_uz",
            field=models.ImageField(
                null=True, upload_to="banner_images/", verbose_name="Image"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=128, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=128, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="category",
            name="name_uz",
            field=models.CharField(max_length=128, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="market",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="market",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="market",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="market",
            name="name_en",
            field=models.CharField(max_length=128, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="market",
            name="name_ru",
            field=models.CharField(max_length=128, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="market",
            name="name_uz",
            field=models.CharField(max_length=128, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="product",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=128, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=128, null=True, verbose_name="Name"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_uz",
            field=models.CharField(max_length=128, null=True, verbose_name="Name"),
        ),
    ]
