# Generated by Django 5.2.5 on 2025-08-15 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="market",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="main.market",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="main.product",
            ),
        ),
    ]
