# Generated by Django 5.2.5 on 2025-08-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_favorite_market_alter_favorite_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
