# Generated by Django 5.2.5 on 2025-11-12 01:51

import django.db.models.deletion
from django.db import migrations, models


def forward_copy_images(apps, schema_editor):
    Product = apps.get_model("main", "Product")
    ProductImage = apps.get_model("main", "ProductImage")
    db_alias = schema_editor.connection.alias

    bulk = []
    for product in Product.objects.using(db_alias).exclude(image=""):
        image_field = getattr(product, "image", None)
        if not image_field:
            continue
        bulk.append(
            ProductImage(
                product_id=product.pk,
                image=image_field,
                position=0,
            )
        )

    if bulk:
        ProductImage.objects.using(db_alias).bulk_create(bulk)


def reverse_copy_images(apps, schema_editor):
    Product = apps.get_model("main", "Product")
    ProductImage = apps.get_model("main", "ProductImage")
    db_alias = schema_editor.connection.alias

    for image in ProductImage.objects.using(db_alias).select_related("product"):
        Product.objects.using(db_alias).filter(pk=image.product_id).update(image=image.image)


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="product_images/", verbose_name="Image"
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(default=0, verbose_name="Position"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product image",
                "verbose_name_plural": "Product images",
                "ordering": ("position", "id"),
            },
        ),
        migrations.RunPython(
            forward_copy_images,
            reverse_copy_images,
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
