# Generated by Django 5.2.5 on 2025-12-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='content',
        ),
        migrations.AddField(
            model_name='oferta',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='oferta_files/', verbose_name='File'),
        ),
    ]
