# Generated by Django 5.2.5 on 2026-01-25 20:51

import apps.main.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_oferta_content_oferta_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[apps.main.models.product.validate_image_size, apps.main.models.product.validate_image_dimensions], verbose_name='Image'),
        ),
    ]
