# Generated by Django 5.2.5 on 2026-01-30 00:00

import apps.main.models.product
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_productimage_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommonProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                ("name_en", models.CharField(max_length=128, null=True, verbose_name="Name")),
                ("name_ru", models.CharField(max_length=128, null=True, verbose_name="Name")),
                ("name_uz", models.CharField(max_length=128, null=True, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                ("description_en", models.TextField(null=True, verbose_name="Description")),
                ("description_ru", models.TextField(null=True, verbose_name="Description")),
                ("description_uz", models.TextField(null=True, verbose_name="Description")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="common_products",
                        to="main.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Common product",
                "verbose_name_plural": "Common products",
            },
        ),
        migrations.CreateModel(
            name="CommonProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to="common_product_images/",
                        validators=[
                            apps.main.models.product.validate_image_size,
                            apps.main.models.product.validate_image_dimensions,
                        ],
                        verbose_name="Image",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0, verbose_name="Position")),
                (
                    "common_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="main.commonproduct",
                        verbose_name="Common product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Common product image",
                "verbose_name_plural": "Common product images",
                "ordering": ("position", "id"),
            },
        ),
        migrations.AddField(
            model_name="product",
            name="common_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="market_products",
                to="main.commonproduct",
                verbose_name="Common product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="main.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Name"),
        ),
    ]
