# Generated by Django 5.2.5 on 2026-03-12 21:03

import apps.main.models.product
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_common_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerlar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='commonproduct',
            options={'verbose_name': 'Umumiy mahsulot', 'verbose_name_plural': 'Umumiy mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='commonproductimage',
            options={'ordering': ('position', 'id'), 'verbose_name': 'Umumiy mahsulot rasmi', 'verbose_name_plural': 'Umumiy mahsulot rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Chegirma', 'verbose_name_plural': 'Chegirmalar'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Sevimli', 'verbose_name_plural': 'Sevimlilar'},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': "Do'kon", 'verbose_name_plural': "Do'konlar"},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Bildirishnoma', 'verbose_name_plural': 'Bildirishnomalar'},
        ),
        migrations.AlterModelOptions(
            name='oferta',
            options={'ordering': ['-created_at'], 'verbose_name': 'Oferta', 'verbose_name_plural': 'Oferta'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('position', 'id'), 'verbose_name': 'Mahsulot rasmi', 'verbose_name_plural': 'Mahsulot rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='usernotification',
            options={'verbose_name': 'Foydalanuvchi bildirishnomasi', 'verbose_name_plural': 'Foydalanuvchi bildirishnomalari'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_en',
            field=models.ImageField(null=True, upload_to='banner_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_ru',
            field=models.ImageField(null=True, upload_to='banner_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image_uz',
            field=models.ImageField(null=True, upload_to='banner_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name="O'rin"),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category_images/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='main.category', verbose_name='Tegishli kategoriya'),
        ),
        migrations.AlterField(
            model_name='commonproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_products', to='main.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='commonproduct',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='commonproduct',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='commonproduct',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='commonproduct',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='commonproduct',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='commonproduct',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='commonproduct',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='commonproduct',
            name='name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='commonproductimage',
            name='common_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.commonproduct', verbose_name='Umumiy mahsulot'),
        ),
        migrations.AlterField(
            model_name='commonproductimage',
            name='image',
            field=models.ImageField(upload_to='common_product_images/', validators=[apps.main.models.product.validate_image_size, apps.main.models.product.validate_image_dimensions], verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='commonproductimage',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name="O'rin"),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='main.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='type',
            field=models.CharField(choices=[('ptc', 'Foiz'), ('fix', "Qat'iy summa")], verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qiymat'),
        ),
        migrations.AlterField(
            model_name='market',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='market',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='market',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='market',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='market',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='market',
            name='end_time',
            field=models.TimeField(verbose_name='Yopilish vaqti'),
        ),
        migrations.AlterField(
            model_name='market',
            name='lat',
            field=models.FloatField(verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='market',
            name='logo',
            field=models.ImageField(upload_to='market_logos/', verbose_name='Logotip'),
        ),
        migrations.AlterField(
            model_name='market',
            name='lon',
            field=models.FloatField(verbose_name='Uzunlik'),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='market',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='market',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='market',
            name='name_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='market',
            name='open_time',
            field=models.TimeField(verbose_name='Ochilish vaqti'),
        ),
        migrations.AlterField(
            model_name='market',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to=settings.AUTH_USER_MODEL, verbose_name='Egasi'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('inactive', 'Nofaol')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='oferta_files/', verbose_name='Fayl'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='main.category', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='common_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='market_products', to='main.commonproduct', verbose_name='Umumiy mahsulot'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chegirmali narx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Chegirma turi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.market', verbose_name="Do'kon"),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_uz',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[apps.main.models.product.validate_image_size, apps.main.models.product.validate_image_dimensions], verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name="O'rin"),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name="O'qilgan"),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='main.notification', verbose_name='Bildirishnoma'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='send_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan sana'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
